// global state types
export const SET_GLOBAL_DATE = "SET_GLOBAL_DATE";
export const RESET_GLOBAL_DATE = "RESET_GLOBAL_DATE";

export const SET_GLOBAL_TEAM = "SET_GLOBAL_TEAM";
export const RESET_GLOBAL_TEAM = "RESET_GLOBAL_TEAM";

// user types
export const REQUEST_REGISTER_USER = "REQUEST_REGISTER_USER";
export const REGISTER_USER_SUCCESSFUL = "REGISTER_USER_SUCCESSFUL";
export const REGISTER_USER_REJECTED = "REGISTER_USER_REJECTED";

export const CONFIRM_USER_REGISTRATION = "CONFIRM_USER_REGISTRATION";
export const CONFIRM_USER_REGISTRATION_SUCCESSFUL =
  "CONFIRM_USER_REGISTRATION_SUCCESSFUL";
export const CONFIRM_USER_REGISTRATION_REJECTED =
  "CONFIRM_USER_REGISTRATION_REJECTED";

// user login types
export const REQUEST_LOGIN_USER = "REQUEST_LOGIN_USER";
export const LOGIN_USER_SUCCESSFUL = "LOGIN_USER_SUCCESSFUL";
export const LOGIN_USER_REJECTED = "LOGIN_USER_REJECTED";

// club types
export const REQUEST_REGISTER_CLUB = "REQUEST_REGISTER_CLUB";
export const REGISTER_CLUB_SUCCESSFUL = "REGISTER_CLUB_SUCCESSFUL";
export const REGISTER_CLUB_REJECTED = "REGISTER_CLUB_REJECTED";

// team types
export const REQUEST_REGISTER_TEAM = "REQUEST_REGISTER_TEAM";
export const REGISTER_TEAM_SUCCESSFUL = "REGISTER_TEAM_SUCCESSFUL";
export const REGISTER_TEAM_REJECTED = "REGISTER_TEAM_REJECTED";

export const GET_TEAMS = "GET_TEAMS";
export const GET_TEAMS_SUCCESSFUL = "GET_TEAMS_SUCCESSFUL";
export const GET_TEAMS_REJECTED = "GET_TEAMS_REJECTED";

// player types
export const REQUEST_REGISTER_PLAYERS = "REQUEST_REGISTER_PLAYERS";
export const REGISTER_PLAYERS_SUCCESSFUL = "REGISTER_PLAYERS_SUCCESSFUL";
export const REGISTER_PLAYERS_REJECTED = "REGISTER_PLAYERS_REJECTED";

export const GET_PLAYERS_REJECTED = "GET_PLAYERS_REJECTED,";
export const GET_PLAYERS_SUCCESSFUL = "  GET_PLAYERS_SUCCESSFUL,";
export const REQUEST_GET_PLAYERS = "  REQUEST_GET_PLAYERS,";

// attendance types
export const RECORD_PLAYERS_ATTENDANCE = "RECORD_PLAYERS_ATTENDANCE";
export const RECORD_PLAYERS_ATTENDANCE_SUCCESSFUL =
  "RECORD_PLAYERS_ATTENDANCE_SUCCESSFUL";
export const RECORD_PLAYERS_ATTENDANCE_REJECTED =
  "RECORD_PLAYERS_ATTENDANCE_REJECTED";

export const GET_PLAYERS_ATTENDANCE = "GET_PLAYERS_ATTENDANCE";
export const GET_PLAYERS_ATTENDANCE_SUCCESSFUL =
  "GET_PLAYERS_ATTENDANCE_SUCCESSFUL";
export const GET_PLAYERS_ATTENDANCE_REJECTED =
  "GET_PLAYERS_ATTENDANCE_REJECTED";
