// user types
export const REQUEST_REGISTER_USER = "REQUEST_REGISTER_USER";
export const REGISTER_USER_SUCCESSFUL = "REGISTER_USER_SUCCESSFUL";
export const REGISTER_USER_REJECTED = "REGISTER_USER_REJECTED";

// club types
export const REQUEST_REGISTER_CLUB = "REQUEST_REGISTER_CLUB";
export const REGISTER_CLUB_SUCCESSFUL = "REGISTER_CLUB_SUCCESSFUL";
export const REGISTER_CLUB_REJECTED = "REGISTER_CLUB_REJECTED";

// team types
export const REQUEST_REGISTER_TEAM = "REQUEST_REGISTER_TEAM";
export const REGISTER_TEAM_SUCCESSFUL = "REGISTER_TEAM_SUCCESSFUL";
export const REGISTER_TEAM_REJECTED = "REGISTER_TEAM_REJECTED";

export const GET_TEAMS = "GET_TEAMS";
export const GET_TEAMS_SUCCESSFUL = "GET_TEAMS_SUCCESSFUL";
export const GET_TEAMS_REJECTED = "GET_TEAMS_REJECTED";

// player types
export const REQUEST_REGISTER_PLAYER = "REQUEST_REGISTER_PLAYER";
export const REGISTER_PLAYER_SUCCESSFUL = "REGISTER_PLAYER_SUCCESSFUL";
export const REGISTER_PLAYER_REJECTED = "REGISTER_PLAYER_REJECTED";
